// When you need a new flag add it here, do not remove flags

public enum Flag
{
    NULLFLAG,
    TESTFLAG,
    OSLO_FORESTDONE,
    OSLO_OPERAPUZZLECOMPLETE,
    OSLO_CASTLEPUZZLECOMPLETE,
    OSLO_LIBRARYDONE,
    OFFICE_ARROW,
    OSLO_ARROW,
    TRONDHEIM_ARROW,
    FOREST_ARROW,
    OSLO_COMPLETE,
    SCHMOOSE_ASKED,
    SCHMOOSE_COMPLETE,

    SCHMOOSE_Q1,
    SCHMOOSE_Q2,
    SCHMOOSE_Q3,
    SCHMOOSE_Q4,
    SCHMOOSE_Q5,
    SCHMOOSE_Q6,
    SCHMOOSE_Q7,
    SCHMOOSE_Q8,
    SCHMOOSE_Q9,
    SCHMOOSE_Q10,
    SCHMOOSE_Q11,
    SCHMOOSE_Q12,
    SCHMOOSE_Q13,
    SCHMOOSE_Q14,
    SCHMOOSE_Q15,
    SCHMOOSE_Q16,
    SCHMOOSE_Q17,
    SCHMOOSE_Q18,
    SCHMOOSE_Q19,
    SCHMOOSE_Q20

}